In [2]:
conda activate tf-gpu


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [4]:
x_train = np.load('x_train2.npy')
y_train = np.load('y_train3.npy')

In [9]:
y_unique = np.unique(y_train)

In [10]:
y_train2 = []
for y in y_train:
    y1 = 0
    for i in range(len(y_unique)):
        if y == y_unique[i]:
            y1 = i
    y_train2.append(y1)

In [11]:
y_train2

[8,
 345,
 131,
 283,
 205,
 303,
 232,
 220,
 1,
 39,
 61,
 355,
 130,
 202,
 290,
 78,
 114,
 119,
 369,
 316,
 265,
 273,
 21,
 342,
 122,
 81,
 211,
 152,
 365,
 92,
 6,
 385,
 373,
 115,
 387,
 284,
 189,
 177,
 180,
 104,
 176,
 347,
 350,
 139,
 1,
 141,
 398,
 326,
 379,
 224,
 14,
 97,
 60,
 276,
 117,
 323,
 147,
 209,
 165,
 144,
 144,
 163,
 271,
 319,
 217,
 181,
 207,
 101,
 77,
 102,
 230,
 277,
 243,
 325,
 44,
 86,
 383,
 49,
 117,
 333,
 341,
 351,
 159,
 316,
 335,
 98,
 166,
 173,
 98,
 68,
 235,
 302,
 219,
 193,
 181,
 136,
 310,
 259,
 258,
 55,
 58,
 174,
 388,
 251,
 161,
 342,
 105,
 397,
 171,
 214,
 169,
 216,
 76,
 117,
 184,
 41,
 343,
 168,
 120,
 287,
 27,
 126,
 259,
 364,
 359,
 317,
 116,
 19,
 17,
 292,
 215,
 278,
 84,
 279,
 200,
 378,
 310,
 181,
 116,
 253,
 43,
 26,
 370,
 45,
 56,
 183,
 1,
 322,
 251,
 213,
 106,
 316,
 305,
 159,
 407,
 337,
 38,
 183,
 231,
 265,
 174,
 409,
 113,
 73,
 210,
 293,
 365,
 400,
 296,
 102,
 110,
 405,
 94,
 20

In [12]:
del(y_train)

In [13]:
y_train = np.array(y_train2)
np.save('y_train3.npy', y_train)

In [5]:
len(x_train)

46710

In [6]:
len(y_train)

46710

In [4]:
x_train.shape

(46710, 3136)

In [8]:
y_train.shape

(46710,)

In [12]:
len(np.unique(y_train))

411

### Model Building

In [5]:
model = Sequential(
    [
        Dense(units = x_train.shape[1], input_dim = x_train.shape[1], activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = (x_train.shape[1])/3, activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = (x_train.shape[1])/3,activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = (x_train.shape[1])/3,activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = (x_train.shape[1])/9,activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = 700,activation = 'relu', activity_regularizer = tf.keras.regularizers.L2(0.1)),
        Dense(units = 411, activation = 'softmax'),
    ]
)

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3136)              9837632   
                                                                 
 dense_1 (Dense)             (None, 1045)              3278165   
                                                                 
 dense_2 (Dense)             (None, 1045)              1093070   
                                                                 
 dense_3 (Dense)             (None, 1045)              1093070   
                                                                 
 dense_4 (Dense)             (None, 348)               364008    
                                                                 
 dense_5 (Dense)             (None, 700)               244300    
                                                                 
 dense_6 (Dense)             (None, 411)               2

In [33]:
model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(),
             optimizer = tf.keras.optimizers.Adam(0.00000001), metrics = ['accuracy'])

In [8]:
type(x_train[0][0])

numpy.uint8

### Training

In [8]:
import os
# checkpoint_path = "C:\Users\rohan\Computer vision\Bird Classification\model1.ckpt"
checkpoint_dir = os.path.dirname('model2.ckpt')

# Create a callback that saves the model's weights
callback = tf.keras.callbacks.ModelCheckpoint(filepath="model2.ckpt",
                                                 save_weights_only=True,
                                                 verbose=1)

In [8]:
model.load_weights('model2.ckpt')

In [21]:
model.get_weights()

[array([[-2.6853155e-02, -1.7214794e-02, -1.7341308e-02, ...,
          4.2582853e-03, -2.2197478e-02, -3.5641130e-02],
        [-1.1511651e-02,  1.7147668e-02, -6.5485602e-03, ...,
         -1.8216918e-03,  3.1926538e-04, -1.9856911e-02],
        [-3.3879329e-02, -2.0199640e-02, -1.1035396e-02, ...,
         -1.8273434e-02, -2.9550482e-02,  1.1052534e-02],
        ...,
        [ 2.8251639e-02,  1.6333427e-02, -2.8085630e-02, ...,
         -3.4920014e-02, -7.1524307e-03, -2.5905628e-02],
        [-2.3474010e-02, -2.2424242e-02,  1.4723068e-03, ...,
         -3.5474915e-02,  2.0537885e-02,  9.5064826e-03],
        [-1.9995827e-02,  1.0195472e-02, -4.6270368e-05, ...,
          1.9590052e-02,  5.8224401e-03, -3.7158499e-03]], dtype=float32),
 array([-0.00770718, -0.00644885, -0.00217193, ..., -0.00486651,
        -0.00606083, -0.00835553], dtype=float32),
 array([[ 0.01428699,  0.03301504, -0.01682446, ...,  0.03458656,
          0.01505344,  0.02218592],
        [-0.03902259, -0.0168405

In [31]:
j = 29000
for i in range(30000, 35000, 1000):
    
    print("Iteration = {}".format(j/1000))
    print()
    model.fit(x_train[j:i], y_train[j:i], epochs = 34, callbacks = [callback])
    j = i
    print()


Iteration = 29.0

Epoch 1/34
32/32 [==============================] - ETA: 0s - loss: 5.8260 - accuracy: 0.0270
Epoch 1: saving model to model2.ckpt
32/32 [==============================] - 2s 58ms/step - loss: 5.8260 - accuracy: 0.0270
Epoch 2/34
31/32 [============================>.] - ETA: 0s - loss: 5.7091 - accuracy: 0.0312
Epoch 2: saving model to model2.ckpt
32/32 [==============================] - 2s 54ms/step - loss: 5.7084 - accuracy: 0.0310
Epoch 3/34
31/32 [============================>.] - ETA: 0s - loss: 5.5969 - accuracy: 0.0363
Epoch 3: saving model to model2.ckpt
32/32 [==============================] - 2s 55ms/step - loss: 5.6049 - accuracy: 0.0360
Epoch 4/34
31/32 [============================>.] - ETA: 0s - loss: 5.5097 - accuracy: 0.0393
Epoch 4: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 5.5121 - accuracy: 0.0390
Epoch 5/34
31/32 [============================>.] - ETA: 0s - loss: 5.4333 - accuracy: 0.0444
Epoch 5: sav

31/32 [============================>.] - ETA: 0s - loss: 5.5309 - accuracy: 0.0403
Epoch 4: saving model to model2.ckpt
32/32 [==============================] - 2s 55ms/step - loss: 5.5348 - accuracy: 0.0400
Epoch 5/34
31/32 [============================>.] - ETA: 0s - loss: 5.4457 - accuracy: 0.0423
Epoch 5: saving model to model2.ckpt
32/32 [==============================] - 2s 55ms/step - loss: 5.4540 - accuracy: 0.0420
Epoch 6/34
31/32 [============================>.] - ETA: 0s - loss: 5.3878 - accuracy: 0.0454
Epoch 6: saving model to model2.ckpt
32/32 [==============================] - 2s 57ms/step - loss: 5.3785 - accuracy: 0.0470
Epoch 7/34
31/32 [============================>.] - ETA: 0s - loss: 5.3095 - accuracy: 0.0494
Epoch 7: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 5.3094 - accuracy: 0.0490
Epoch 8/34
31/32 [============================>.] - ETA: 0s - loss: 5.2454 - accuracy: 0.0625
Epoch 8: saving model to model2.ckpt
32/3

31/32 [============================>.] - ETA: 0s - loss: 5.2934 - accuracy: 0.0655
Epoch 7: saving model to model2.ckpt
32/32 [==============================] - 2s 53ms/step - loss: 5.2912 - accuracy: 0.0650
Epoch 8/34
31/32 [============================>.] - ETA: 0s - loss: 5.2225 - accuracy: 0.0685
Epoch 8: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 5.2256 - accuracy: 0.0690
Epoch 9/34
31/32 [============================>.] - ETA: 0s - loss: 5.1626 - accuracy: 0.0756
Epoch 9: saving model to model2.ckpt
32/32 [==============================] - 2s 57ms/step - loss: 5.1637 - accuracy: 0.0750
Epoch 10/34
31/32 [============================>.] - ETA: 0s - loss: 5.1023 - accuracy: 0.0746
Epoch 10: saving model to model2.ckpt
32/32 [==============================] - 2s 58ms/step - loss: 5.1048 - accuracy: 0.0740
Epoch 11/34
31/32 [============================>.] - ETA: 0s - loss: 5.0510 - accuracy: 0.0887
Epoch 11: saving model to model2.ckpt


31/32 [============================>.] - ETA: 0s - loss: 5.0438 - accuracy: 0.1008
Epoch 10: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 5.0429 - accuracy: 0.1010
Epoch 11/34
31/32 [============================>.] - ETA: 0s - loss: 4.9888 - accuracy: 0.0998
Epoch 11: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 4.9843 - accuracy: 0.1020
Epoch 12/34
31/32 [============================>.] - ETA: 0s - loss: 4.9295 - accuracy: 0.1099
Epoch 12: saving model to model2.ckpt
32/32 [==============================] - 2s 55ms/step - loss: 4.9248 - accuracy: 0.1100
Epoch 13/34
31/32 [============================>.] - ETA: 0s - loss: 4.8692 - accuracy: 0.1129
Epoch 13: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 4.8671 - accuracy: 0.1140
Epoch 14/34
31/32 [============================>.] - ETA: 0s - loss: 4.8123 - accuracy: 0.1220
Epoch 14: saving model to model2.

31/32 [============================>.] - ETA: 0s - loss: 4.8041 - accuracy: 0.1048
Epoch 13: saving model to model2.ckpt
32/32 [==============================] - 2s 56ms/step - loss: 4.7961 - accuracy: 0.1070
Epoch 14/34
31/32 [============================>.] - ETA: 0s - loss: 4.7291 - accuracy: 0.1159
Epoch 14: saving model to model2.ckpt
32/32 [==============================] - 2s 55ms/step - loss: 4.7369 - accuracy: 0.1150
Epoch 15/34
31/32 [============================>.] - ETA: 0s - loss: 4.6840 - accuracy: 0.1220
Epoch 15: saving model to model2.ckpt
32/32 [==============================] - 2s 54ms/step - loss: 4.6819 - accuracy: 0.1210
Epoch 16/34
31/32 [============================>.] - ETA: 0s - loss: 4.6271 - accuracy: 0.1321
Epoch 16: saving model to model2.ckpt
32/32 [==============================] - 2s 54ms/step - loss: 4.6269 - accuracy: 0.1320
Epoch 17/34
31/32 [============================>.] - ETA: 0s - loss: 4.5721 - accuracy: 0.1401
Epoch 17: saving model to model2.

In [10]:
model.get_weights()

[array([[-2.6853155e-02, -1.7214794e-02, -1.7341308e-02, ...,
          4.2582853e-03, -2.2197478e-02, -3.5641130e-02],
        [-1.1511651e-02,  1.7147668e-02, -6.5485602e-03, ...,
         -1.8216918e-03,  3.1926538e-04, -1.9856911e-02],
        [-3.3879329e-02, -2.0199640e-02, -1.1035396e-02, ...,
         -1.8273434e-02, -2.9550482e-02,  1.1052534e-02],
        ...,
        [ 2.8251639e-02,  1.6333427e-02, -2.8085630e-02, ...,
         -3.4920014e-02, -7.1524307e-03, -2.5905628e-02],
        [-2.3474010e-02, -2.2424242e-02,  1.4723068e-03, ...,
         -3.5474915e-02,  2.0537885e-02,  9.5064826e-03],
        [-1.9995827e-02,  1.0195472e-02, -4.6270368e-05, ...,
          1.9590052e-02,  5.8224401e-03, -3.7158499e-03]], dtype=float32),
 array([-0.00770718, -0.00644885, -0.00217193, ..., -0.00486651,
        -0.00606083, -0.00835553], dtype=float32),
 array([[ 0.01428699,  0.03301504, -0.01682446, ...,  0.03458656,
          0.01505344,  0.02218592],
        [-0.03902259, -0.0168405

In [10]:
x_cv = np.load('x_cv2.npy')
y_cv = np.load('y_cv.npy')

In [12]:
train_pred = model.predict(x_train[:5000])

157/157 [==============================] - 0s 3ms/step


array([0.0000000e+00, 1.3856624e-38, 1.7502921e-38, ..., 9.9988079e-01,
       9.9998021e-01, 9.9999869e-01], dtype=float32)

In [26]:
y_pred = model.predict(x_cv)

365/365 [==============================] - 2s 4ms/step


In [27]:
tf.nn.softmax(y_pred).numpy()

array([[0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604],
       [0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604],
       [0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604],
       ...,
       [0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604],
       [0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604],
       [0.00243429, 0.00243268, 0.00243473, ..., 0.0024319 , 0.00243123,
        0.00243604]], dtype=float32)

In [11]:
y_cv_unique = np.unique(y_cv)
y_cv2 = []
for y in y_cv:
    y1 = 0
    for i in range(len(y_cv_unique)):
        if y == y_cv_unique[i]:
            y1 = i
    y_cv2.append(y1)

In [12]:
del(y_cv)

In [13]:
y_cv = np.array(y_cv2)
y_cv

array([ 96, 281,  51, ..., 290, 256, 271])

In [ ]:
unique

In [15]:
train_pred2 = []
for arr in train_pred:
    i = list(arr).index(max(arr))
    train_pred2.append(i)
    

NameError: name 'train_pred' is not defined

In [ ]:
train_pred2 = []
for arr in train_pred:
    i = list(arr).index(max(arr))
    train_pred2.append(i)


In [ ]:
x

In [19]:
cv_pred = model.predict(x_cv)

365/365 [==============================] - 2s 5ms/step


In [22]:
y_pred = []
for i in cv_pred:
    y = list(i).index(max(i))
    y_pred.append(y)

In [23]:
y_pred

[237,
 13,
 327,
 407,
 407,
 407,
 296,
 318,
 407,
 296,
 296,
 189,
 189,
 75,
 189,
 235,
 407,
 234,
 296,
 132,
 151,
 119,
 6,
 151,
 158,
 151,
 322,
 1,
 296,
 403,
 6,
 114,
 107,
 296,
 119,
 189,
 189,
 407,
 193,
 175,
 409,
 45,
 114,
 159,
 175,
 296,
 403,
 327,
 189,
 407,
 193,
 193,
 114,
 189,
 296,
 189,
 297,
 151,
 75,
 114,
 381,
 237,
 407,
 231,
 151,
 189,
 381,
 33,
 407,
 175,
 72,
 407,
 407,
 189,
 114,
 407,
 159,
 119,
 407,
 292,
 13,
 189,
 193,
 296,
 407,
 75,
 193,
 193,
 105,
 175,
 75,
 296,
 234,
 189,
 296,
 322,
 296,
 101,
 193,
 13,
 92,
 322,
 296,
 322,
 114,
 119,
 189,
 1,
 114,
 151,
 92,
 159,
 296,
 189,
 92,
 114,
 407,
 407,
 189,
 212,
 189,
 187,
 407,
 189,
 72,
 409,
 13,
 119,
 119,
 407,
 407,
 189,
 254,
 189,
 242,
 33,
 6,
 238,
 296,
 407,
 13,
 13,
 189,
 322,
 407,
 407,
 114,
 189,
 206,
 75,
 75,
 296,
 193,
 296,
 340,
 211,
 407,
 322,
 1,
 237,
 151,
 407,
 235,
 55,
 409,
 175,
 407,
 119,
 114,
 407,
 254,
 296,
 

In [30]:
y_cv

array([ 96, 281,  51, ..., 290, 256, 271])

In [32]:
model.evaluate(x_cv[:34000], y_cv[:34000])

365/365 [==============================] - 2s 6ms/step - loss: 12.5193 - accuracy: 0.0034


[12.519343376159668, 0.0034252440091222525]

In [18]:
score[1]*100

NameError: name 'score' is not defined

In [11]:
np.unique(y_pred2)

array([148])

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y_cv, y_pred)

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets